import { defineConfig } from "drizzle-kit"

// drizzle-kit remains SQLite-only. Per plan decision #7, the PG backend uses
// a fresh bootstrap (single 0000_init.sql), NOT a port of the 37 SQLite TS
// migrations. The blessed PG SQL lives at .opencode/db-migrations/0000_init.sql
// (Athena's signed executable form, Memo #5/#6) and is executed by the PG
// migration runner (migration.pg.ts) — NOT generated by drizzle-kit. Wiring
// drizzle-kit PG generation here would clobber the SQLite-generated
// schema.gen.ts/migration.gen.ts, which must never be hand-edited.
export default defineConfig({
  dialect: "sqlite",
  schema: ["./src/**/*.sql.ts", "./src/**/sql.ts"],
  out: "./migration",
  dbCredentials: {
    url: "/home/thdxr/.local/share/opencode/opencode.db",
  },
})
